apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "motion-detector.fullname" . }}-config
data:
  STREAM_URL: "{{ .Values.configMap.data.STREAM_URL }}"
  DISCORD_WEBHOOK_URL: "{{ .Values.configMap.data.DISCORD_WEBHOOK_URL }}"