kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: motion-detector-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: "motion-detector-pv"
