apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "camera.fullname" . }}-config
data:
  INTERNAL_TOKEN: "{{ .Values.configMap.data.INTERNAL_TOKEN }}"
  CONFIG_URL: "{{ .Values.configMap.data.CONFIG_URL }}"